# Alembic configuration file
# This file is the config for the Alembic environment.

# path to migration files
script_location = alembic

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the directory where the script lives
prepended_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to zoneinfo.ZoneInfo()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# set to 40 to truncate at 40 characters
# (be careful, this might result in duplicate
# migration file names)
# truncate_slug_len = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Uncomment and set to logging config file
# logging_config = 

# log level to which the console should be set to
# see SQLAlchemy docs for current logging patterns
sqlalchemylogging_level = WARN
